// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// RsIron Generator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by rs_iron code generator
// Entry point: lib/app_module.dart
// Components found: 14

import 'package:rs_iron/rs_iron.dart';

import 'bloc/user_bloc.dart';
import 'datasources/user_datasources.dart';
import 'examples/router_context_examples.dart';
import 'repositories/user_repository.dart';
import 'repositories/user_repository_impl.dart';
import 'services/database_service.dart';
import 'services/notification_service.dart';
import 'services/router_service.dart';
import 'services/user_service.dart';
import 'usecases/user_usecases.dart';

extension GeneratedDependencies on IronContainer {
  /// Register all discovered components from the entire project
  void registerGeneratedDependencies() {
    // Register UserBloc
    register<UserBloc>(() {
      final instance = UserBloc(get<UserRepository>());
      return instance;
    }, scope: ScopeType.singleton);

    // Register UserApiDataSource
    register<UserApiDataSource>(
      () => UserApiDataSource(),
      scope: ScopeType.singleton,
    );

    // Register UserLocalDataSource
    register<UserLocalDataSource>(
      () => UserLocalDataSource(),
      scope: ScopeType.singleton,
    );

    // Register RouterContextExamples
    register<RouterContextExamples>(
      () => RouterContextExamples(),
      scope: ScopeType.singleton,
    );

    // Register ExampleUsageService
    register<ExampleUsageService>(
      () => ExampleUsageService(),
      scope: ScopeType.singleton,
    );

    // Register UserRepositoryImpl
    register<UserRepository>(() {
      final instance = UserRepositoryImpl();
      instance.databaseService = get<DatabaseService>();
      instance.configService = get<ConfigurationService>();
      instance.apiDataSource = get<UserApiDataSource>();
      instance.localDataSource = get<UserLocalDataSource>();
      return instance;
    }, scope: ScopeType.singleton);

    // Register DatabaseService
    register<DatabaseService>(
      () => DatabaseService(),
      scope: ScopeType.singleton,
    );

    // Register ConfigurationService
    register<ConfigurationService>(
      () => ConfigurationService(),
      scope: ScopeType.singleton,
    );

    // Register NotificationService
    register<NotificationService>(
      () => NotificationService(),
      scope: ScopeType.singleton,
    );

    // Register RouterService
    register<RouterService>(() => RouterService(), scope: ScopeType.singleton);

    // Register UserService
    register<UserService>(() {
      final instance = UserService(get<ConfigurationService>());
      instance.userRepository = get<UserRepository>();
      return instance;
    }, scope: ScopeType.singleton);

    // Register GetAllUsersUseCase
    register<GetAllUsersUseCase>(() {
      final instance = GetAllUsersUseCase();
      instance.userRepository = get<UserRepository>();
      return instance;
    }, scope: ScopeType.singleton);

    // Register CreateUserUseCase
    register<CreateUserUseCase>(() {
      final instance = CreateUserUseCase();
      instance.userRepository = get<UserRepository>();
      return instance;
    }, scope: ScopeType.singleton);

    // Register DeleteUserUseCase
    register<DeleteUserUseCase>(() {
      final instance = DeleteUserUseCase();
      instance.userRepository = get<UserRepository>();
      return instance;
    }, scope: ScopeType.singleton);
  }
}

/// Convenience mixin that provides direct property access to DI components.
/// Add this mixin to your StatefulWidget states for easy dependency access.
///
/// Example:
/// ```dart
/// class _MyWidgetState extends State<MyWidget> with IronCore, IronMixin {
///   @override
///   Widget build(BuildContext context) {
///     return Text(userService.getCurrentUser()); // Ironct access!
///   }
/// }
/// ```
mixin IronMixin {
  /// Get UserBloc instance from DI container
  UserBloc get userBloc {
    if (this is IronCore) {
      return (this as IronCore).get<UserBloc>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserBloc instance from DI container (async)
  Future<UserBloc> get userBlocAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<UserBloc>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserApiDataSource instance from DI container
  UserApiDataSource get userApiDataSource {
    if (this is IronCore) {
      return (this as IronCore).get<UserApiDataSource>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserApiDataSource instance from DI container (async)
  Future<UserApiDataSource> get userApiDataSourceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<UserApiDataSource>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserLocalDataSource instance from DI container
  UserLocalDataSource get userLocalDataSource {
    if (this is IronCore) {
      return (this as IronCore).get<UserLocalDataSource>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserLocalDataSource instance from DI container (async)
  Future<UserLocalDataSource> get userLocalDataSourceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<UserLocalDataSource>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get RouterContextExamples instance from DI container
  RouterContextExamples get routerContextExamples {
    if (this is IronCore) {
      return (this as IronCore).get<RouterContextExamples>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get RouterContextExamples instance from DI container (async)
  Future<RouterContextExamples> get routerContextExamplesAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<RouterContextExamples>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get ExampleUsageService instance from DI container
  ExampleUsageService get exampleUsageService {
    if (this is IronCore) {
      return (this as IronCore).get<ExampleUsageService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get ExampleUsageService instance from DI container (async)
  Future<ExampleUsageService> get exampleUsageServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<ExampleUsageService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserRepository instance from DI container
  UserRepository get userRepository {
    if (this is IronCore) {
      return (this as IronCore).get<UserRepository>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserRepository instance from DI container (async)
  Future<UserRepository> get userRepositoryAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<UserRepository>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get DatabaseService instance from DI container
  DatabaseService get databaseService {
    if (this is IronCore) {
      return (this as IronCore).get<DatabaseService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get DatabaseService instance from DI container (async)
  Future<DatabaseService> get databaseServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<DatabaseService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get ConfigurationService instance from DI container
  ConfigurationService get configurationService {
    if (this is IronCore) {
      return (this as IronCore).get<ConfigurationService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get ConfigurationService instance from DI container (async)
  Future<ConfigurationService> get configurationServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<ConfigurationService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get NotificationService instance from DI container
  NotificationService get notificationService {
    if (this is IronCore) {
      return (this as IronCore).get<NotificationService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get NotificationService instance from DI container (async)
  Future<NotificationService> get notificationServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<NotificationService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get RouterService instance from DI container
  RouterService get routerService {
    if (this is IronCore) {
      return (this as IronCore).get<RouterService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get RouterService instance from DI container (async)
  Future<RouterService> get routerServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<RouterService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserService instance from DI container
  UserService get userService {
    if (this is IronCore) {
      return (this as IronCore).get<UserService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get UserService instance from DI container (async)
  Future<UserService> get userServiceAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<UserService>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get GetAllUsersUseCase instance from DI container
  GetAllUsersUseCase get getAllUsersUseCase {
    if (this is IronCore) {
      return (this as IronCore).get<GetAllUsersUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get GetAllUsersUseCase instance from DI container (async)
  Future<GetAllUsersUseCase> get getAllUsersUseCaseAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<GetAllUsersUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get CreateUserUseCase instance from DI container
  CreateUserUseCase get createUserUseCase {
    if (this is IronCore) {
      return (this as IronCore).get<CreateUserUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get CreateUserUseCase instance from DI container (async)
  Future<CreateUserUseCase> get createUserUseCaseAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<CreateUserUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get DeleteUserUseCase instance from DI container
  DeleteUserUseCase get deleteUserUseCase {
    if (this is IronCore) {
      return (this as IronCore).get<DeleteUserUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }

  /// Get DeleteUserUseCase instance from DI container (async)
  Future<DeleteUserUseCase> get deleteUserUseCaseAsync async {
    if (this is IronCore) {
      return (this as IronCore).getAsync<DeleteUserUseCase>();
    }
    throw StateError(
      'IronMixin must be used with IronCore. '
      'Add "with IronCore, IronMixin" to your class.',
    );
  }
}
